services:
  postgres:
    image: postgres:16
    container_name: dfs-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dfs_user
      POSTGRES_PASSWORD: dfs_pass
      POSTGRES_DB: dfs_db
    networks:
      - internal_network

  master-node:
    build:
      context: master-node
      dockerfile: master-node.Dockerfile
    container_name: dfs-master-node
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dfs_db
      SPRING_DATASOURCE_USERNAME: dfs_user
      SPRING_DATASOURCE_PASSWORD: dfs_pass
    networks:
      - internal_network

  gateway-api:
    build:
      context: gateway-api
      dockerfile: gateway-api.Dockerfile
    container_name: dfs-gateway-api
    ports:
      - "8080:8080"
    networks:
      - internal_network
      - public_network

  file-node1:
    build:
      context: file-node
      dockerfile: file-node1.Dockerfile
    container_name: dfs-file-node1
    networks:
      - internal_network

  file-node2:
    build:
      context: file-node
      dockerfile: file-node2.Dockerfile
    container_name: dfs-file-node2
    environment:
      - SERVER_PORT=8083
    ports:
      - "8083:8083"
    networks:
      - internal_network

  file-node3:
    build:
      context: file-node
      dockerfile: file-node3.Dockerfile
    container_name: dfs-file-node3
    environment:
      - SERVER_PORT=8084
    ports:
      - "8084:8084"
    networks:
      - internal_network

networks:
  public_network:
    driver: bridge
  internal_network:
    driver: bridge
    internal: true